name: BERT

desc_encoder:
  _target_: source.encoder.BERTEncoder.BERTEncoder
  architecture: bert-base-uncased

code_encoder:
  _target_: source.encoder.BERTEncoder.BERTEncoder
  architecture: bert-base-uncased

hidden_size: 768

tokenizer:
  architecture: ${model.desc_encoder.architecture}


desc_frequency_opt: 1
code_frequency_opt: 1


lr: 2e-5


loss:
  _target_: source.loss.NPairLoss.NPairLoss
  params:
    name: NPairLoss
    scale: 20